

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up secret key
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        AES_KEY: ${{ secrets.AES_KEY }}
    - name: Use secret key
      run: |
        echo "SECRET_KEY is $SECRET_KEY"
        echo "ALGORITHM is $ALGORITHM"
        echo "AES_KEY is $AES_KEY"

    - name: Test with pytest
      run: |
        python -m pytest . 